//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> CounterpartyId { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
