//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderConstruction
    {
        public int Id { get; set; }
        public int NumberOfProucts { get; set; }
        public decimal Price { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserOrderId { get; set; }
        public Nullable<int> ProductSizeId { get; set; }
    
        public virtual ProductSize ProductSize { get; set; }
        public virtual UserOrder UserOrder { get; set; }
    }
}
