//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOrder()
        {
            this.OrderConstruction = new HashSet<OrderConstruction>();
        }
    
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateOfShipment { get; set; }
        public Nullable<int> CounterpartyId { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderConstruction> OrderConstruction { get; set; }
    }
}
